Solution/WebApp-Biblioteca/WebApp-Biblioteca/Models/EntidadesBiblioteca/Administrador.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_Biblioteca.Models.EntidadesBiblioteca
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Administrador()
        {
            this.Preguntas = new HashSet<Pregunta>();
            this.TipoPrestamoes = new HashSet<TipoPrestamo>();
        }
    
        public int idAdministrador { get; set; }
        public string correo { get; set; }
        public string nombre { get; set; }
        public string contrasena { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pregunta> Preguntas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoPrestamo> TipoPrestamoes { get; set; }
    }
}

Solution/WebApp-Biblioteca/WebApp-Biblioteca/Controllers/AdministradorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp_Biblioteca.Models.EntidadesBiblioteca;
using WebApp_Biblioteca.Models.Filter;

namespace WebApp_Biblioteca.Controllers
{
    public class AdministradorController : Controller
    {
        // GET: Login
        public ActionResult IniciarSesion() {
            return View();
        }

        [HttpPost]
        public ActionResult IniciarSesion(Administrador admin) {
            using (Entities dbcon = new Entities())
            {
                var nombre = dbcon.SP_login_administrador(admin.correo, admin.contrasena).ToList();
                if (nombre.Count != 0)
                {
                    Administrador admins = new Administrador();
                    admins = dbcon.Administradors.Where(x => x.correo == admin.correo).FirstOrDefault();
                    Session["idAdministrador"] = admins.idAdministrador;
                    return Redirect("Menu");
                }
                else
                {
                    ViewBag.Error = " <label class='alert alert-danger text - center' >Credenciales incorrectas</label>";
                    return View();
                }
                
            }
        }

        [UserAuthFilter]
        public ActionResult Menu() {
            return View();
        }

        [HttpGet]
        public ActionResult LogOff()
        {
            Session.Abandon();
            Session.Clear();
            return RedirectToAction("Index","Home");
        }

    }
}

Solution/WebApp-Biblioteca/WebApp-Biblioteca/Controllers/ExportarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using WebApp_Biblioteca.Models;
using WebApp_Biblioteca.Models.EntidadesBiblioteca;
using WebApp_Biblioteca.Models.Filter;

namespace WebApp_Biblioteca.Controllers
{
    [UserAuthFilter]
    public class ExportarController : Controller
    {
        // GET: Exportar
        public ActionResult Datos()
        {
            using (Entities dbcon = new Entities())
            {
                var table = new DataTable();
                var cmd = dbcon.Database.Connection.CreateCommand();
                cmd.CommandText = "exec SP_Select_dataset";

                cmd.Connection.Open();
                table.Load(cmd.ExecuteReader());

                //var result = dbcon.SP_Select_dataset().ToList();
                //var rawdata = dbcon.Database.SqlQuery<ExportarDatos>("Select p.matricula, p.Carrera, f.Sexo, i.Instituto, e.Edad, PE.Etnia, S.Semestre from (	select matricula,titulo,respuesta as Carrera from pregunta left join respuesta on pregunta.idPregunta = respuesta.idPregunta inner join alumno on alumno.idAlumno = respuesta.idAlumno where visible = 1 and titulo = 'Carrera')p left join (		select matricula,titulo,respuesta as Sexo from pregunta left join respuesta on pregunta.idPregunta = respuesta.idPregunta inner join alumno on alumno.idAlumno = respuesta.idAlumno where visible = 1	and titulo = 'Sexo' )f on p.matricula = f.matricula 	left join (select matricula,titulo,respuesta as Instituto from pregunta left join respuesta on pregunta.idPregunta = respuesta.idPregunta inner join alumno on alumno.idAlumno = respuesta.idAlumno where visible = 1 	and titulo = 'Instituto')i on i.matricula = p.matricula left join (select matricula,titulo,respuesta as Edad from pregunta left join respuesta on pregunta.idPregunta = respuesta.idPregunta inner join alumno on alumno.idAlumno = respuesta.idAlumno where visible = 1	and titulo = 'Edad')E on e.matricula = p.matricula		left join (select matricula,titulo,respuesta as Etnia from pregunta left join respuesta on pregunta.idPregunta = respuesta.idPregunta inner join alumno on alumno.idAlumno = respuesta.idAlumno where visible = 1	and titulo = 'Etnia')PE on PE.matricula = p.matricula left join (select matricula,titulo,respuesta as Semestre from pregunta left join respuesta on pregunta.idPregunta = respuesta.idPregunta inner join alumno on alumno.idAlumno = respuesta.idAlumno where visible = 1	and titulo = 'Semestre')S on S.matricula = p.matricula").ToList();

                return View(table);
            }
        }


        public FileResult DescargarReporte()
        {
            using (Entities dbcon = new Entities())
            {
                var table = new DataTable();
                var cmd = dbcon.Database.Connection.CreateCommand();
                cmd.CommandText = "exec SP_Select_dataset";

                cmd.Connection.Open();
                table.Load(cmd.ExecuteReader());

                var sb = new StringBuilder();
                IEnumerable<string> columnNames = table.Columns.Cast<DataColumn>().
                                  Select(column => column.ColumnName);
                sb.AppendLine(string.Join(",", columnNames));

                foreach (DataRow row in table.Rows)
                {
                    IEnumerable<string> fields = row.ItemArray.Select(field => field.ToString());
                    sb.AppendLine(string.Join(",", fields));
                }
                return File(new UTF8Encoding().GetBytes(sb.ToString()), "text/csv", "ReportePreguntas.csv");
            }
        }

        public FileResult ReportePrestamos()
        {
            using (Entities dbcon = new Entities())
            {
                dbcon.SP_respaldarPrestamos();
                var lstData = dbcon.vw_reportePrestamos.ToList();// var lstData = new DataDbHandler().GetDetails();
                var sb = new StringBuilder();
                sb.AppendLine("id" + "," + "idAlumno" + "," + "TipoPrestamo" + ", " + "Fecha" );

                foreach (var data in lstData)
                {
                    sb.AppendLine(data.id + "," + data.idAlumno + "," + data.TipoPrestamo + ", " + data.fecha);
                }
                return File(new UTF8Encoding().GetBytes(sb.ToString()), "text/csv", "ReportePrestamos.csv");
            }
        }

        public FileResult RecuperarDatos() {
            using (Entities dbcon = new Entities())
            {
                var lstData = dbcon.vw_datosHistoricos.ToList();// var lstData = new DataDbHandler().GetDetails();
                var sb = new StringBuilder();
                sb.AppendLine("IdRegistro" + "," + "Pregunta" + "," + "Respuesta" + ", " + "idAlumno" + ", " + "fechaRespuesta" + ", " + "fechaBorrado");

                foreach (var data in lstData)
                {
                    sb.AppendLine(data.idRegistro + "," + data.titulo + ","+data.respuesta+", "+data.idAlumno+", "+data.fechaRespuesta + ", " + data.fechaBorrado);
                }
                return File(new UTF8Encoding().GetBytes(sb.ToString()), "text/csv", "Reporte.csv");
            }
        }



        [HttpPost]
        public ActionResult Datos(FormCollection form) {
            foreach (var key in form.AllKeys)
            {
                using (Entities dbcon = new Entities())
                {
                    int x = int.Parse(form[key]);

                    if (x == 1)
                    {
                        //borrar datos
                        dbcon.sp_respaldarInformacion();
                        dbcon.sp_D_borrarRespuestas();
                    }
                    else
                    {
                        return Redirect("RecuperarDatos");
                    }

                }


            }

            return Redirect("Datos");
        }
    }
}

Solution/WebApp-Biblioteca/WebApp-Biblioteca/Views/Administrador/IniciarSesion.cshtml
@model WebApp_Biblioteca.Models.EntidadesBiblioteca.Administrador

@{
    ViewBag.Title = "IniciarSesion";
}

<h2>IniciarSesion</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Administrador</h4>
    @Html.Raw((String)ViewBag.Error)
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">

        <div class="form-group">
            @Html.LabelFor(model => model.correo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.correo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.correo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.contrasena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.contrasena, new { htmlAttributes = new { @class = "form-control",@type = "password" } })
                @Html.ValidationMessageFor(model => model.contrasena, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Iniciar" class="btn btn-default" /><br />
            </div>

        </div>

    </div>

</div>
}

Solution/WebApp-Biblioteca/WebApp-Biblioteca/Views/Administrador/Login.cshtml
@model WebApp_Biblioteca.Models.EntidadesBiblioteca.Administrador

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Administrador</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.correo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.correo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.correo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.contrasena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.contrasena, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.contrasena, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Menu")
</div>

Solution/WebApp-Biblioteca/WebApp-Biblioteca/Views/Administrador/Menu.cshtml
@{
    ViewBag.Title = "Menu";
}
<style>
    .btn-squared-default-plain {
        width: 300px !important;
        height: 300px !important;
        font-size: 40px;
        margin: 10px;
    }

        .btn-squared-default-plain:hover {
            border: 0px solid white;
        }
</style>
<h2>Menu</h2>


<a href="@Url.Action("ListaPreguntas","Pregunta")" class="btn btn-squared-default-plain btn-primary"><br /><br />Preguntas</a>
<a href="@Url.Action("ListaTipoPrestamos","TipoPrestamo")" class="btn btn-squared-default-plain btn-success"><br /><br />Prestamos</a>
<a href="@Url.Action("Datos","Exportar")" class="btn btn-squared-default-plain btn-warning"><br /><br />Reporte</a>
<a href="@Url.Action("LogOff", "Administrador",FormMethod.Post)" class="btn btn-squared-default-plain btn-danger"><br /><br />Cerrar Sesión</a>